/* Generated By:JavaCC: Do not edit this line. AnalisadorTreeConstants.java Version 5.0 */
public interface AnalisadorTreeConstants
{
  public int JJTPROCESSA = 0;
  public int JJTGOAL = 1;
  public int JJTMAINCLASS = 2;
  public int JJTCLASSDECLARATION = 3;
  public int JJTVARDECLARATION = 4;
  public int JJTMETHODDECLARATION = 5;
  public int JJTTYPE = 6;
  public int JJTSTATEMENT = 7;
  public int JJTEXPRESSION = 8;
  public int JJTEXPRESSION1 = 9;
  public int JJTIDENTIFIER = 10;


  public String[] jjtNodeName = {
    "processa",
    "goal",
    "mainClass",
    "classDeclaration",
    "varDeclaration",
    "methodDeclaration",
    "type",
    "statement",
    "expression",
    "expression1",
    "identifier",
  };
}
/* JavaCC - OriginalChecksum=0aaa2c3d46786630343458518f7f5df0 (do not edit this line) */
