/* Generated By:JavaCC: Do not edit this line. AnalisadorVisitor.java Version 5.0 */
public interface AnalisadorVisitor
{
  public Object visit(SimpleNode node, Controlador data);
  public Object visit(processa node, Controlador data);
  public Object visit(goal node, Controlador data);
  public Object visit(mainClass node, Controlador data);
  public Object visit(classDeclaration node, Controlador data);
  public Object visit(varDeclaration node, Controlador data);
  public Object visit(methodDeclaration node, Controlador data);
  public Object visit(type node, Controlador data);
  public Object visit(statement node, Controlador data);
  public Object visit(expression node, Controlador data);
  public Object visit(expression1 node, Controlador data);
}
/* JavaCC - OriginalChecksum=97a5b784bafd576e2e730b414af21fc4 (do not edit this line) */
