/* Generated By:JavaCC: Do not edit this line. AnalisadorTreeConstants.java Version 5.0 */
public interface AnalisadorTreeConstants
{
  public int JJTPROCESSA = 0;
  public int JJTGOAL = 1;
  public int JJTMAINCLASS = 2;
  public int JJTCLASSDECLARATION = 3;
  public int JJTVARDECLARATION = 4;
  public int JJTMETHODDECLARATION = 5;
  public int JJTTYPE = 6;
  public int JJTSTATEMENT = 7;
  public int JJTEXPRESSION = 8;
  public int JJTEXPRESSION1 = 9;


  public String[] jjtNodeName = {
    "processa",
    "goal",
    "mainClass",
    "classDeclaration",
    "varDeclaration",
    "methodDeclaration",
    "type",
    "statement",
    "expression",
    "expression1",
  };
}
/* JavaCC - OriginalChecksum=14383bc5b14565a607b78bbd73b93fae (do not edit this line) */
