/* Generated By:JJTree: Do not edit this line. expression1.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class expression1 extends CustomNode {
  public expression1(int id) {
    super(id);
  }

  public expression1(Analisador p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AnalisadorVisitor visitor, Controlador data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=55ea3d931a40939088c07b278468e7c5 (do not edit this line) */
