/* Generated By:JJTree: Do not edit this line. type.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class type extends CustomNode {
  public type(int id) {
    super(id);
  }

  public type(Analisador p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AnalisadorVisitor visitor, Controlador data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=80a820cc19ac349501e32696257c8718 (do not edit this line) */
